apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: graylog
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.250
  selector:
    app: graylog
  ports:
    - name: web
      port: 9000
      targetPort: 9000
    - name: gelf-udp
      port: 12201
      protocol: UDP
      targetPort: 12201