kind: Namespace
apiVersion: v1
metadata:
  name: courses
  labels:
    name: courses
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: courses-pv
  namespace: courses
  labels: 
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/courses-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: courses-pvc
  namespace: courses
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses-deployment
  namespace: courses
spec:
  replicas: 3
  selector:
    matchLabels:
      app: courses
  template:
    metadata:
      labels:
        app: courses
    spec:
      containers:
        - name: courses
          image: courses-img:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: courses-volume
              mountPath: /mnt/courses-data
          ports:
            - containerPort: 80
      volumes:
        - name: courses-volume
          persistentVolumeClaim:
            claimName: courses-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: courses-service
  namespace: courses
  labels:
    app: courses
spec:
  selector:
    app: courses
  ports:
    - protocol: TCP
      port: 80 # Port exposé par le service
      targetPort: 80 # Port sur lequel le pod écoute
      nodePort: 30001
  type: LoadBalancer # Type de service (ClusterIP, NodePort, LoadBalancer)

