apiVersion: batch/v1
kind: Job
metadata:
  name: inject-demo-products
  namespace: elk
spec:
  template:
    spec:
      containers:
        - name: inject
          image: curlimages/curl:7.85.0
          command:
            - sh
            - -c
            - |
              echo "Injection de données dans Elasticsearch..."
              for i in $(seq 1 5); do
                curl -X POST http://192.168.10.151:9200/demo-products/_doc/$i \
                  -H 'Content-Type: application/json' \
                  -d "{
                    \"name\": \"Widget $i\",
                    \"price\": $((20 + i * 5)),
                    \"in_stock\": true,
                    \"timestamp\": \"$(date -Iseconds)\"
                  }"
              done
              echo "✅ Données injectées"
      restartPolicy: Never
  backoffLimit: 2