apiVersion: v1
kind: Service
metadata:
  name: kibana-lb
  namespace: elk
spec:
  type: LoadBalancer
  loadBalancerIP: ${KIBANA_IP}
  selector:
    kibana.k8s.elastic.co/name: quickstart
  ports:
  - port: 5601
    targetPort: 5601