apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard # Minikube utilise 'standard' par défaut
  hostPath:
    path: "/data/jenkins" # Dossier interne à l'instance Minikube