apiVersion: v1
kind: Pod
metadata:
  name: restore-jenkins
  namespace: jenkins
spec:
  containers:
  - name: restore
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /restore
      name: jenkins-home
  volumes:
  - name: jenkins-home
    persistentVolumeClaim:
      claimName: jenkins-pvc
