replicas: 1
minimumMasterNodes: 1

nodeGroup: "master"
roles:
  - master
  - data
  - ingest

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "local-path"
  resources:
    requests:
      storage: 5Gi

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

esJavaOpts: "-Xms512m -Xmx512m"

# PAS de readinessProbe → évite les erreurs de validation
readinessProbe: {}

# PAS d’initContainer → évite les erreurs de sécurité
sysctlInitContainer:
  enabled: false

# Compatible avec PodSecurityAdmission
securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]

esConfig:
  elasticsearch.yml: |
    discovery.type: single-node
    xpack.security.enabled: false
    xpack.ml.enabled: false
    bootstrap.memory_lock: false
    bootstrap.system_call_filter: false
    network.host: 0.0.0.0