# ============================================================
# Namespace
# ============================================================
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-system
---
# ============================================================
# Elasticsearch Deployment + Service
# ============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elastic-system
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.security.transport.ssl.enabled
              value: "false"
            - name: xpack.security.http.ssl.enabled
              value: "false"
          volumeMounts:
            - name: esdata
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: esdata
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elastic-system
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
  type: ClusterIP
---
# ============================================================
# Kibana Deployment + LoadBalancer Service (MetalLB)
# ============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elastic-system
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.15.3
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch.elastic-system.svc.cluster.local:9200"
            - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
              value: "none"
            - name: XPACK_SECURITY_ENABLED
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elastic-system
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  ports:
    - name: http
      port: 5601
      targetPort: 5601
  type: LoadBalancer
  loadBalancerIP: ${KIBANA_IP}
---
# # ============================================================
# # Filebeat DaemonSet
# # ============================================================
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: filebeat
#   namespace: elastic-system
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: filebeat
# rules:
#   - apiGroups: [""]
#     resources: ["pods", "namespaces", "nodes"]
#     verbs: ["get", "list", "watch"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: filebeat
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: filebeat
# subjects:
#   - kind: ServiceAccount
#     name: filebeat
#     namespace: elastic-system
# ---
# apiVersion: apps/v1
# kind: DaemonSet
# metadata:
#   name: filebeat
#   namespace: elastic-system
#   labels:
#     app: filebeat
# spec:
#   selector:
#     matchLabels:
#       app: filebeat
#   template:
#     metadata:
#       labels:
#         app: filebeat
#     spec:
#       serviceAccountName: filebeat
#       containers:
#         - name: filebeat
#           image: docker.elastic.co/beats/filebeat:8.15.3
#           args: ["-e"]
#           env:
#             - name: ELASTICSEARCH_HOST
#               value: "elasticsearch.elastic-system.svc.cluster.local"
#             - name: ELASTICSEARCH_PORT
#               value: "9200"
#           volumeMounts:
#             - name: varlog
#               mountPath: /var/log
#             - name: containers
#               mountPath: /var/lib/docker/containers
#               readOnly: true
#       volumes:
#         - name: varlog
#           hostPath:
#             path: /var/log
#         - name: containers
#           hostPath:
#             path: /var/lib/docker/containers
# ---
# ============================================================
# Metricbeat DaemonSet
# ============================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metricbeat
  namespace: elastic-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricbeat
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "namespaces", "endpoints"]
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metricbeat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metricbeat
subjects:
  - kind: ServiceAccount
    name: metricbeat
    namespace: elastic-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metricbeat
  namespace: elastic-system
  labels:
    app: metricbeat
spec:
  selector:
    matchLabels:
      app: metricbeat
  template:
    metadata:
      labels:
        app: metricbeat
    spec:
      serviceAccountName: metricbeat
      containers:
        - name: metricbeat
          image: docker.elastic.co/beats/metricbeat:8.15.3
          args: ["-e", "-system.hostfs=/hostfs"]
          env:
            - name: ELASTICSEARCH_HOST
              value: "elasticsearch.elastic-system.svc.cluster.local"
            - name: ELASTICSEARCH_PORT
              value: "9200"
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: proc
              mountPath: /hostfs/proc
              readOnly: true
            - name: sysfs
              mountPath: /hostfs/sys/fs/cgroup
              readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sysfs
          hostPath:
            path: /sys/fs/cgroup
