apiVersion: v1
kind: Namespace
metadata:
  name: elastic-system
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: elastic-system
type: Opaque
data:
  ELASTIC_PASSWORD: ZWxhc3RpY19zZWNyZXQ=          # base64("elastic_secret")
  KIBANA_SYSTEM_PASSWORD: TW9uTW90RGVQYXNzZUZvcnQ= # base64("MonMotDePasseFort")
  BEATS_SYSTEM_PASSWORD: YmVhdHNfc2VjcmV0          # base64("beats_secret")
  LOGSTASH_SYSTEM_PASSWORD: bG9nc3Rhc2hfc2VjcmV0   # base64("logstash_secret")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
          ports:
            - containerPort: 9200
          env:
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: ELASTIC_PASSWORD
            - name: discovery.type
              value: "single-node"
            - name: xpack.security.enabled
              value: "true"
            - name: xpack.security.http.ssl.enabled
              value: "false"   # 🔑 TLS désactivé pour HTTP clair
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  type: LoadBalancer
  loadBalancerIP: ${ES_IP}   # IP fournie par ta variable d'environnement
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elastic-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.15.3
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch.elastic-system.svc.cluster.local:9200"
            - name: ELASTICSEARCH_USERNAME
              value: "kibana_system"
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: KIBANA_SYSTEM_PASSWORD
          volumeMounts:
            - name: kibana-dashboard
              mountPath: /usr/share/kibana/config/dashboards
      volumes:
        - name: kibana-dashboard
          configMap:
            name: kibana-dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elastic-system
spec:
  type: LoadBalancer
  loadBalancerIP: ${KIBANA_IP}   # IP fournie par ta variable d'environnement
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-dashboard
  namespace: elastic-system
data:
  dashboard.json: |
    {
      "title": "Logs Overview",
      "panels": [
        {
          "type": "visualization",
          "title": "Logs per Host",
          "visState": {
            "type": "histogram",
            "params": {
              "interval": "auto",
              "field": "host.name"
            }
          }
        },
        {
          "type": "visualization",
          "title": "Error Rate",
          "visState": {
            "type": "metric",
            "params": {
              "field": "log.level",
              "filter": "ERROR"
            }
          }
        }
      ]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat
  namespace: elastic-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:8.15.3
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch.elastic-system.svc.cluster.local:9200"
            - name: ELASTICSEARCH_USERNAME
              value: "beats_system"
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: BEATS_SYSTEM_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricbeat
  namespace: elastic-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metricbeat
  template:
    metadata:
      labels:
        app: metricbeat
    spec:
      containers:
        - name: metricbeat
          image: docker.elastic.co/beats/metricbeat:8.15.3
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch.elastic-system.svc.cluster.local:9200"
            - name: ELASTICSEARCH_USERNAME
              value: "beats_system"
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: BEATS_SYSTEM_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elastic-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.15.3
          ports:
            - containerPort: 5044
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch.elastic-system.svc.cluster.local:9200"
            - name: ELASTICSEARCH_USERNAME
              value: "logstash_system"
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: LOGSTASH_SYSTEM_PASSWORD
          volumeMounts:
            - name: logstash-pipeline
              mountPath: /usr/share/logstash/pipeline
      volumes:
        - name: logstash-pipeline
          configMap:
            name: logstash-pipeline
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: elastic-system
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    output {
      elasticsearch {
        hosts => ["http://${ES_IP}:9200"]
        user => "logstash_system"
        password => "${LOGSTASH_SYSTEM_PASSWORD}"
        index => "logs-%{+YYYY.MM.dd}"
      }
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: elastic-init-users
  namespace: elastic-system
spec:
  template:
    spec:
      containers:
        - name: init-users
          image: curlimages/curl:8.5.0
          command: ["sh", "-c"]
          args:
            - |
              ELASTIC_PASS=$(kubectl get secret elastic-credentials -n elastic-system -o jsonpath='{.data.ELASTIC_PASSWORD}' | base64 -d);
              KIBANA_PASS=$(kubectl get secret elastic-credentials -n elastic-system -o jsonpath='{.data.KIBANA_SYSTEM_PASSWORD}' | base64 -d);
              BEATS_PASS=$(kubectl get secret elastic-credentials -n elastic-system -o jsonpath='{.data.BEATS_SYSTEM_PASSWORD}' | base64 -d);
              LOGSTASH_PASS=$(kubectl get secret elastic-credentials -n elastic-system -o jsonpath='{.data.LOGSTASH_SYSTEM_PASSWORD}' | base64 -d);

              echo "⏳ Attente qu'Elasticsearch soit prêt..."
              until curl -s -u elastic:$ELASTIC_PASS http://elasticsearch:9200/_cluster/health | grep -q '"status"'; do
                echo "Elasticsearch pas encore prêt, retry dans 5s..."
                sleep 5
              done

              echo "✅ Elasticsearch prêt, configuration des comptes système..."
              curl -u elastic:$ELASTIC_PASS -X POST http://elasticsearch:9200/_security/user/kibana_system/_password \
                -H 'Content-Type: application/json' -d "{\"password\":\"$KIBANA_PASS\"}"
              curl -u elastic:$ELASTIC_PASS -X POST http://elasticsearch:9200/_security/user/beats_system/_password \
                -H 'Content-Type: application/json' -d "{\"password\":\"$BEATS_PASS\"}"
              curl -u elastic:$ELASTIC_PASS -X POST http://elasticsearch:9200/_security/user/logstash_system/_password \
                -H 'Content-Type: application/json' -d "{\"password\":\"$LOGSTASH_PASS\"}"
      restartPolicy: OnFailure