apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elastic-system
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.15.3
          ports:
            - containerPort: 5044   # Beats input
            - containerPort: 9600   # Monitoring API
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch.elastic-system.svc.cluster.local:9200"
            - name: ELASTICSEARCH_USERNAME
              value: "logstash_system"
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: LOGSTASH_SYSTEM_PASSWORD
          volumeMounts:
            - name: logstash-pipeline
              mountPath: /usr/share/logstash/pipeline
      volumes:
        - name: logstash-pipeline
          configMap:
            name: logstash-pipeline
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elastic-system
spec:
  selector:
    app: logstash
  ports:
    - name: beats
      port: 5044
      targetPort: 5044
    - name: monitoring
      port: 9600
      targetPort: 9600