apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: elastic-system
type: Opaque
data:
  ELASTIC_PASSWORD: ZWxhc3RpY19zZWNyZXQ=          # base64("elastic_secret")
  KIBANA_SYSTEM_PASSWORD: TW9uTW90RGVQYXNzZUZvcnQ= # base64("MonMotDePasseFort")
  BEATS_SYSTEM_PASSWORD: YmVhdHNfc2VjcmV0          # base64("beats_secret")
  LOGSTASH_SYSTEM_PASSWORD: bG9nc3Rhc2hfc2VjcmV0   # base64("logstash_secret")